#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/veradesk/veradesk /usr/bin/veradesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/veradesk.service ]; then
			rm /etc/systemd/system/veradesk.service /usr/lib/systemd/system/veradesk.service /usr/lib/systemd/user/veradesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/veradesk/files/systemd/veradesk.service /usr/lib/systemd/system/veradesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload veradesk.service: Unit veradesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/veradesk.service:10: Executable path is not absolute: pkill -f "veradesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/veradesk.service
		fi
		systemctl daemon-reload
		systemctl enable veradesk
		systemctl start veradesk
	fi
fi
